name: SBT Run Tests

on:
  push:
    branches: [ trm ]
  pull_request:
    branches: [ trm ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: sbt +test
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_ACCESS }}
